---
- name: This playbook is used to fetch ec2 info based on environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Gather info 
    ec2_instance_facts:
      region: us-east-1
      filters:
        "tag:Env": dev
    register: env_info

  - name: Display env info
    debug:
      msg: "{{ item.instance_id }}"
    with_items: "{{ env_info.instances }}"
