---
- name: Lets generate the info and send to manager
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    virginia: us-east-1

  tasks:
  - name: Getting info about ec2 instance
    ec2_instance_facts:
      region: "{{ virginia }}"
      filters:
        "tag:Env": dev
    register: manager

  - name: generate csv
    template:
      src: generate_csv.j2
      dest: ec2_instance_info.csv 
